### PR TITLE
Remove underscore

### PR DESCRIPTION
**Pull request by exussum12**

### CODE REVIEW

**Comment by vikkio88** [comment]
could you remove it from the dependencies too?

**Comment by vikkio88** [comment]
oh fuck it, I will do it myself :smile:

**Comment by exussum12** [comment]
Can the yarn.lock file go too ?

**Comment by IonutBajescu** [comment]
★★★★☆
Quality PR but Scott didn't pay the gif tribute. I'd be willing to change my rating if the issue will be fixed in a timely manner.

**Pull request merged**
